Repository Marmalade-ai/company-website, pull requests merged in 2021-07, with the labels that each got.

#11 Fixed social media links.
  src/components/layout/Footer.js
Labels: enhancement

#15 License link specified.
  README.md
Labels: documentation

#16 Fixed links in Header navigation bar.
  src/components/layout/Header.js
  src/pages/index.js
Labels: fix

#19 Added Code of Conduct page.
  src/components/layout/Footer.js
  src/pages/code-of-conduct.js
Labels: enhancement

#21 Defines global semantic CSS tags in 'tailwind.css'.
  src/components/layout/Footer.js
  src/css/tailwind.css
  src/pages/code-of-conduct.js
  src/pages/index.js
  src/pages/privacy-policy.js
Labels: refactor

#25 Customized 404 error page.
  src/pages/404.js
Labels: enhancement

#26 Refactored to use semantic HTML where possible.
  src/components/layout/Footer.js
  src/components/layout/Header.js
  src/css/tailwind.css
  src/pages/code-of-conduct.js
  src/pages/privacy-policy.js
Labels: refactor

#27 Adjusts text and button colors closer to the logo colors.
  tailwind.config.js
Labels: refactor

#30 Added copyright notice to footer.
  src/components/layout/Footer.js
Labels: enhancement

#36 Added content for biographies.
  README.md
  src/components/layout/Footer.js
  src/components/layout/Header.js
  src/css/tailwind.css
  src/images/craig_fisk_headshot.jpg
  src/images/jim_tyhurst_headshot.jpg
  src/pages/404.js
  src/pages/about.js
  src/pages/code-of-conduct.js
  src/pages/index.js
  src/pages/privacy-policy.js
  tailwind.config.js
Labels: enhancement

#38 Adds content for 'Our Mission' on 'About' page
  src/components/layout/Footer.js
  src/css/tailwind.css
  src/images/michael_porto_headshot.jpg
  src/images/vivian_tran_headshot.jpg
  src/pages/about.js
  src/pages/index.js
Labels: enhancement

#37 First draft of `About` page.
  src/components/layout/Footer.js
  src/css/tailwind.css
  src/images/craig_fisk_headshot.jpg
  src/images/jim_tyhurst_headshot.jpg
  src/images/michael_porto_headshot.jpg
  src/images/vivian_tran_headshot.jpg
  src/pages/about.js
  src/pages/index.js
Labels: enhancement

#39 Added dependencies for deployment to Gatsby Cloud.
  gatsby-config.js
  package-lock.json
  package.json
Labels: enhancement

#40 Install `gatsby-source-filesystem`.
  package-lock.json
  package.json
Labels: enhancement

#41 Added content for features and benefits.
  src/components/layout/Footer.js
  src/components/layout/Header.js
  src/pages/index.js
Labels: enhancement

#42 Removed old sample code.
  README.md
  package.json
  src/components/CustomerCard.js
  src/components/LabelText.js
  src/components/StatsBox.js
  src/data/customer-data.js
  src/pages/code-of-conduct.js
  src/pages/privacy-policy.js
  src/svg/LogoIcon.js
  src/svg/SvgCharts.js
Labels: refactor

#47 Removed Gatsby theme
  README.md
  gatsby-config.js
  package-lock.json
  package.json
  postcss.config.js
  src/pages/index.js
  tailwind.config.js
Labels: refactor

#48 Update to Gatsby 3.9.1
  package-lock.json
  package.json
Labels: refactor

#53 Reduced image sizes to improve load time performance.
  .gitignore
  src/components/layout/Header.js
  src/images/chatting.jpg
  src/images/marmalade-logo-lg.jpg
  src/images/marmalade-logo-sm.jpg
  src/images/matching.jpg
  src/images/networking.jpg
Labels: performance

#58 Improved documentation of developer workflow.
  README.md
Labels: documentation

#59 Minor edit to append previous changes.
  README.md
Labels: documentation

#60 Changed title and subtitle on landing page.
  src/pages/index.js
Labels: enhancement

#64 Changed the title of home page.
  src/pages/index.js
Labels: enhancement

#65 Configured `eslint` and `prettier`
  .eslintignore
  .eslintrc
  .eslintrc.json
  .prettierignore
  .prettierrc
  .prettierrc.json
  .vscode/settings.json
  README.md
  gatsby-config.js
  package-lock.json
  package.json
  postcss.config.js
  src/components/Button.js
  src/components/Card.js
  src/components/SplitSection.js
  src/components/layout/Footer.js
  src/components/layout/Header.js
  src/components/layout/Layout.js
  src/pages/404.js
  src/pages/about.js
  src/pages/code-of-conduct.js
  src/pages/index.js
  src/pages/privacy-policy.js
  tailwind.config.js
Labels: enhancement

#66 Specify 1 column for small screens.
  src/pages/about.js
Labels: enhancement

#68 "added favicon and page titles"
  gatsby-config.js
  package-lock.json
  package.json
  src/components/seo.js
  src/pages/about.js
  src/pages/code-of-conduct.js
  src/pages/index.js
  src/pages/privacy-policy.js
Labels: enhancement
