Repository Marmalade-ai/company-website, pull requests merged in 2021-10, with the labels that each got.

#162 Added bold to the captions.
  package-lock.json
  src/css/tailwind.css
  src/pages/communities.js
  src/pages/communities/digital-marketing.js
  src/pages/communities/machine-learning.js
  src/pages/communities/ux-design.js
Labels: enhancement, completed

#163 On code-of-conduct.js page, fixed link to FAQ.
  src/pages/code-of-conduct.js
Labels: fixed

#168 Removed reference to Early Access Lounge.
  src/pages/faq.js
Labels: completed

#170 Uses Tailwind CSS idiom for centering items vertically in flex layout.
  src/css/tailwind.css
  src/pages/communities.js
  src/pages/communities/digital-marketing.js
  src/pages/communities/machine-learning.js
  src/pages/communities/ux-design.js
Labels: completed

#172 Changes font size of section heading elements h1, h2, h3 based on screen size
  src/components/SplitSection.js
  src/css/tailwind.css
  src/pages/about.js
  src/pages/communities.js
  src/pages/communities/digital-marketing.js
  src/pages/communities/machine-learning.js
  src/pages/communities/ux-design.js
  src/pages/index.js
Labels: fixed
