Repository Marmalade-ai/company-website, pull requests merged in 2021-09, with the labels that each got.

#128 Click links branch
  gatsby-config.js
  package-lock.json
  package.json
  src/components/layout/Footer.js
Labels: enhancement

#104 Form to register for Early Access to peer networking.
  src/css/tailwind.css
  src/pages/alphaApplicationFormAccepted.js
  src/pages/alphaGoogleForm.js
  src/pages/index.js
Labels: enhancement

#83 Upgraded dev tools.
  package-lock.json
  package.json
Labels: refactor

#133 Enables testing dev server from other machines on local network
  gatsby-config.js
  package.json
Labels: enhancement

#134 Added 'title' attribute to images.
  src/components/layout/Header.js
  src/pages/about.js
  src/pages/communities/digital-marketing.js
  src/pages/communities/machine-learning.js
  src/pages/communities/ux-design.js
  src/pages/index.js
  src/svg/HeroImage.js
Labels: enhancement

#135 Added Twitter icon next to Twitter link in footer.
  package-lock.json
  package.json
  src/components/layout/Footer.js
Labels: enhancement

#143 Lists vscode extensions needed by developers.
  README.md
Labels: documentation

#142 Connected the alphaGoogleForm on the niche pages
  src/pages/communities/digital-marketing.js
  src/pages/communities/machine-learning.js
  src/pages/communities/ux-design.js
  src/pages/faq.js
Labels: fixed

#145 Rework draft of homepage.
  src/pages/index.js
Labels: fixed

#144 Added <Link> to apply for Early Access in the text of the FAQ.
  src/pages/faq.js
Labels: enhancement

#146 Tuned vertical spacing on multiple pages to improve visual layout
  src/components/SplitSection.js
  src/components/layout/Footer.js
  src/components/layout/Layout.js
  src/pages/about.js
  src/pages/communities.js
  src/pages/communities/digital-marketing.js
  src/pages/communities/machine-learning.js
  src/pages/communities/ux-design.js
  src/pages/faq.js
  src/pages/index.js
  tailwind.config.js
Labels: completed

#148 Restructured 'About' page
  src/pages/about.js
  src/pages/communities.js
  src/pages/faq.js
Labels: completed

#149 Adds credit for Jujube Li in the 'About' page
  package-lock.json
  src/pages/about.js
Labels: enhancement, completed

#152 Try icons for communities level icons
  src/css/tailwind.css
  src/images/UXdesign_soil_32.png
  src/images/UXdesign_soil_64.png
  src/images/digitalmarketing_earth_32.png
  src/images/digitalmarketing_earth_64.png
  src/images/istockphoto-1220226086-400.jpg
  src/images/machinelearning_minerals_32.png
  src/images/machinelearning_minerals_64.png
  src/pages/communities.js
  src/pages/communities/digital-marketing.js
  src/pages/communities/machine-learning.js
  src/pages/communities/ux-design.js
  src/pages/index.js
Labels: enhancement

#150 Added networking with computer screen photo in homepage.
  src/images/istockphoto-1220226086-400.jpg
  src/pages/index.js
Labels: enhancement

#153 Replaced "iStock" watermarked homepage networking image with non-wate…
  src/images/iStockphoto-1220226086-400.jpg
  src/images/istockphoto-1220226086-400.jpg
  src/pages/index.js
Labels: defect, enhancement

#154 Improved readability of niche pages
  src/pages/communities/digital-marketing.js
  src/pages/communities/machine-learning.js
  src/pages/communities/ux-design.js
Labels: enhancement

#155 Revised FAQ content
  src/css/tailwind.css
  src/pages/about.js
  src/pages/faq.js
Labels: completed

#159 Added a `Contact Us` page.
  src/components/layout/Footer.js
  src/pages/contact.js
  src/pages/faq.js
Labels: completed
