Repository Marmalade-ai/company-website, pull requests merged in 2021-08, with the labels that each got.

#73 Adds new content
  src/components/Button.js
  src/components/layout/Footer.js
  src/components/layout/Header.js
  src/pages/about.js
  src/pages/faq.js
  src/pages/index.js
  src/pages/terms-of-service.js
Labels: enhancement

#74 Replaced networking image.
  src/images/networking.jpg
Labels: enhancement

#75 Uses PurgeCSS to reduce size of build
  gatsby-config.js
  package-lock.json
  package.json
  tailwind.config.js
Labels: enhancement, refactor

#84 Resized logo to square 300 x 300 pixels.
  gatsby-config.js
  src/images/marmalade-logo-sm.jpg
  src/images/marmalade-logo-tiny.png
Labels: fix

#86 Fixed company name.
  src/pages/about.js
Labels: fix

#88 Moved 'Forum' link to the footer.
  src/components/layout/Footer.js
  src/pages/index.js
Labels: refactor

#92 Removed 'Login' button.
  src/components/layout/Header.js
Labels: refactor

#95 Added responsive flow for footer sections.
  src/components/layout/Footer.js
  tailwind.config.js
Labels: refactor

#96 Uses consistent flex classes.
  src/components/layout/Footer.js
Labels: refactor

#98 Fixed typo.
  src/pages/privacy-policy.js
Labels: fix

#102 Removed unimplemented links
  src/components/layout/Footer.js
  src/pages/terms-of-service.js
Labels: fix

#103 Removed 'Choosing a Plan' table, which included pricing information.
  src/pages/index.js
Labels: fix

#97 Uses Google Tag Manager to track page views
  gatsby-config.js
  package-lock.json
  package.json
  src/components/layout/Header.js
  src/pages/faq.js
Labels: enhancement

#107 Community pages
  .vscode/settings.json
  src/components/layout/Footer.js
  src/components/layout/Header.js
  src/css/tailwind.css
  src/images/christina-wocintechchat-com-J7EDyqUwXJI-unsplash_300.jpg
  src/images/kobu-agency-7okkFhxrxNw-unsplash_300.jpg
  src/images/pandas_screenshot_300.png
  src/images/pexels-freeboilergrants-7119258_300.jpg
  src/images/stephen-phillips-hostreviews-co-uk-shr_Xn8S8QU-unsplash_300.jpg
  src/images/taras-shypka-iFSvn82XfGo-unsplash_300.jpg
  src/pages/about.js
  src/pages/code-of-conduct.js
  src/pages/communities.js
  src/pages/communities/digital-marketing.js
  src/pages/communities/machine-learning.js
  src/pages/communities/ux-design.js
  src/pages/faq.js
  src/pages/privacy-policy.js
Labels: enhancement

#108 Revised content in FAQ and home page.
  src/pages/faq.js
  src/pages/index.js
Labels: enhancement

#110 Enhanced content in communities pages.
  src/pages/about.js
  src/pages/communities/digital-marketing.js
  src/pages/communities/machine-learning.js
  src/pages/communities/ux-design.js
  src/pages/index.js
Labels: enhancement

#111 Minor grammar edits in `Communities` pages.
  src/pages/communities/digital-marketing.js
  src/pages/communities/machine-learning.js
  src/pages/communities/ux-design.js
Labels: enhancement

#124 Changed company name to a link to home.
  src/components/layout/Header.js
Labels: enhancement
